### ISSUE TITLE
Map error in "Stone of Wisdom"

### ISSUE THREAD

**Issue by kpeamon** [awlck/frankendrift#43]
When playing Stone of Wisdom ( https://www.adrift.co/game/1513 ), the map gives an error: 
"Unhandled exception has occured in your application. If you click continue the application will ignore this error" etc etc.

And then: "Failed, matrix is degenerate"

The long list of details at the bottom of this text.

You can quickly reproduce the error by starting the game and typing:
E, light lamp, E, E, SE, SE. I can keep playing but the map is one big red cross. Played on Windows 10 Home with Frankendrift 0.6.1
DETAILS:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Failed, matrix is degenerate.
   at GShark.Core.Matrix.Decompose(Matrix m, Int32[]& permutation)
   at GShark.Fitting.Curve.SolveCtrlPts(List`1 pts, Matrix coeffMatrix)
   at GShark.Fitting.Curve.Interpolated(List`1 pts, Int32 degree, Nullable`1 startTangent, Nullable`1 endTangent, Boolean centripetal)
   at FrankenDrift.Runner.GraphicsExtensions.DrawCurve(Graphics gfx, Pen pen, Point[] pts) in C:\Users\Adrian\Documents\Development\NetCore\frankendrift\FrankenDrift.Runner\FrankenDrift.Runner\AdriftMap.cs:line 84
   at FrankenDrift.Runner.AdriftMap.DrawLinks(Graphics gfx, MapNode node, DirectionsEnum dir)
   at FrankenDrift.Runner.AdriftMap.DrawNode(Graphics gfx, MapNode node) in C:\Users\Adrian\Documents\Development\NetCore\frankendrift\FrankenDrift.Runner\FrankenDrift.Runner\AdriftMap.cs:line 483
   at FrankenDrift.Runner.MapContent.MapContentOnPaint(Object sender, PaintEventArgs e) in C:\Users\Adrian\Documents\Development\NetCore\frankendrift\FrankenDrift.Runner\FrankenDrift.Runner\AdriftMap.cs:line 783
   at Eto.Forms.Drawable.OnPaint(PaintEventArgs e)
   at Eto.Forms.Drawable.Callback.OnPaint(Drawable widget, PaintEventArgs e)
   at Eto.WinForms.Forms.Controls.DrawableHandler.OnPaint(PaintEventArgs e)
   at Eto.WinForms.Forms.Controls.DrawableHandler.EtoDrawable.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
FrankenDrift.Runner.Win
    Assembly Version: 0.6.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
FrankenDrift.Runner
    Assembly Version: 0.6.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Eto
    Assembly Version: 2.7.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
FrankenDrift.Glue
    Assembly Version: 0.5.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Eto.WinForms
    Assembly Version: 2.7.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.4.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.4.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
FrankenDrift.Adrift
    Assembly Version: 0.6.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.VisualBasic.Core
    Assembly Version: 11.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.4.0.12
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Users/kp/Documents/_SPIL/IFprograms/Frankendrift/frankendrift-v0.6.1.winx64/System.Private.Xml.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
GShark
    Assembly Version: 1.5.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------

************** JIT Debugging **************

**Comment by awlck** [comment]
I've made some changes in 20254750cd60299381479ec05164fa20a832ecf7 so at least we no longer crash the entire interpreter over map drawing issues.
